PythonTBC/urls.py
from django.conf.urls import patterns, include, url
import tbc_error_page.views
import commentingapp.views
import django.contrib.sitemaps.views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from .sitemap import TbcBookSitemap
sitemaps = { 
    'book': TbcBookSitemap, 
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'PythonTBC.views.home', name='home'),
    # url(r'^PythonTBC/', include('PythonTBC.foo.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin', include(admin.site.urls)),
    url(r'^', include('tbc.urls', namespace='tbc')),
    url(r'^sitemap\.xml$', django.contrib.sitemaps.views.sitemap, {'sitemaps': sitemaps}),

    url(r'^admin-tools/commenting', commentingapp.views.commenting, name = 'commenting'),
    url(r'^admin-tools/error_page', tbc_error_page.views.error, name = 'error_page'),
    url(r'^admin-tools/broken_page', tbc_error_page.views.broken, name = 'broken_page'),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]

comments/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^new/$', 'comments.views.new_comment', name='new_comment'),
    url(r'^get/$', 'comments.views.get_comments', name='new_comment'),
    url(r'^new-reply/$', 'comments.views.new_reply', name='new_reply'),
)

tbc/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import tbc.views

urlpatterns = [
    url(r'^$', tbc.views.home, name='home'),
    url(r'^internship-forms/$', tbc.views.internship_forms, name='internship_forms'),
    url(r'^about-pythontbc/$', tbc.views.about_pytbc, name='about_pytbc'),
   
    url(r'^sample-notebook/$', tbc.views.sample_ipynb, name='sample_ipynb'),
    url(r'^register/$', tbc.views.user_register, name='user_register'),
    url(r'^login/$', tbc.views.user_login, name='user_login'),
    url(r'^logout/$', tbc.views.user_logout, name='user_logout'),
    url(r'^profile/$', tbc.views.user_profile, name='user_profile'),
    url(r'^update-profile/$', tbc.views.update_profile, name='update_profile'),
    url(r'^forgot-password/$', tbc.views.forgot_password, name='forgot_password'),
    url(r'^update-password/$', tbc.views.update_password, name='update_password'),
    url(r'^admin-tools/$', tbc.views.admin_tools, name='admin_tools'),    
   
    url(r'^submit-proposal/$', tbc.views.submit_proposal, name='submit_proposal'),
    url(r'^submit-aicte-proposal/$', tbc.views.list_aicte, name='list_aicte'),
    url(r'^submit-aicte-proposal/(?P<aicte_book_id>\d+)/$', tbc.views.submit_aicte_proposal, name='submit_aicte_proposal'),
    url(r'^submit-book/$', tbc.views.submit_book, name='submit_book'),
    url(r'^submit-sample/$', tbc.views.submit_sample, name='submit_sample'),
    url(r'^submit-sample/(?P<proposal_id>\d+)$', tbc.views.submit_sample, name='submit_sample'),
    url(r'^submit-sample/(?P<proposal_id>\d+)/(?P<old_notebook_id>\d+)$', tbc.views.submit_sample, name='submit_sample'),
    url(r'^confirm-book-details/$', tbc.views.confirm_book_details, name='confirm_book_details'),
    url(r'^submit-book-old/$', tbc.views.submit_book, name='submit_book'),
    url(r'^submit-code/$', tbc.views.submit_code, name='submit_code'),
    url(r'^submit-code-old/(?P<book_id>\d+)$', tbc.views.submit_code_old, name='submit_code_old'),
    url(r'^update-content/(?P<book_id>\d+)$', tbc.views.update_content, name='update_content'),
    url(r'^get-zip/(?P<book_id>\d+)$', tbc.views.get_zip, name='get_zip'),
    url(r'^browse-books/$', tbc.views.browse_books, name='browse_books'),
    url(r'^browse-books/(?P<category>.+)$', tbc.views.browse_books, name='browse_books'),
    url(r'^convert-notebook/(?P<notebook_path>.+)$', tbc.views.convert_notebook, name='convert_notebook'),
    url(r'^book-details/(?P<book_id>\d+)/$', tbc.views.book_details, name='book_details'),
	url(r'^completed-books/$', tbc.views.completed_books, name='completed_books'),
	url(r'^completed-books/(?P<category>.+)$', tbc.views.completed_books, name='completed_books'),
	url(r'^books-under-progress/$', tbc.views.books_under_progress, name='books_under_progress'),
	url(r'^redirect-ipynb/(?P<notebook_path>.+)$', tbc.views.redirect_to_ipynb, name='redirect_to_ipynb'),
	url(r'^get-certificate/$', tbc.views.get_certificate, name='get_certificate'),
	url(r'^get-certificate/(?P<book_id>\d+)/$', tbc.views.get_certificate, name='get_certificate'),
    
    
    url(r'^book-review/$', tbc.views.book_review, name='book_review'),
    url(r'^proposal-review/$', tbc.views.review_proposals, name='review_proposals'),
    url(r'^proposal-review/(?P<proposal_id>\d+)/(?P<textbook_id>\d+)$', tbc.views.review_proposals, name='review_proposals'),
    url(r'^disapprove-sample-notebook/(?P<proposal_id>\d+)$', tbc.views.disapprove_proposal, name='disapprove_proposal'),
    url(r'^allot-book/(?P<proposal_id>\d+)$', tbc.views.allot_book, name='allot_book'),
    url(r'^reject-proposal/(?P<proposal_id>\d+)$', tbc.views.reject_proposal, name='reject_proposal'),
    url(r'^book-review/(?P<book_id>\d+)$', tbc.views.book_review, name='book_review'),
    url(r'^approve-book/(?P<book_id>\d+)$', tbc.views.approve_book, name='approve_book'),
    url(r'^notify-changes/(?P<book_id>\d+)$', tbc.views.notify_changes, name='notify_changes'),
    url(r'^brokenbooks/$', tbc.views.get_broken_books, name='broken_books'),
    url(r'^link-image/$', tbc.views.link_image, name='link_image'),
    url(r'^books/$', tbc.views.books, name='books'),
    url(r'^edit-book/(?P<book_id>\d+)/$', tbc.views.edit_book, name='edit_book'),
    url(r'^books-fill-details/$', tbc.views.books_fill_details, name='books_fill_details'),
    url(r'^edit-books-fill-details/(?P<book_id>\d+)/$', tbc.views.edit_books_fill_details, name='edit_books_fill_details'),
    # ajax urls
    url(r'^ajax/matching-books/$', tbc.views.ajax_matching_books, name='AjaxMatchingBooks'),

]

comments/models.py
from django.db import models

class Comment(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    book = models.CharField(max_length=200)
    chapter = models.CharField(max_length=10)
    example = models.CharField(max_length=10)
    page = models.CharField(max_length=10)
    email = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

class Reply(models.Model):
    comment = models.ForeignKey(Comment)
    body = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

comments/forms.py
from django import forms

class CommentForm(forms.Form):
    book = forms.CharField(widget=forms.HiddenInput())
    chapter = forms.CharField(widget=forms.HiddenInput())
    example = forms.CharField(widget=forms.HiddenInput())
    page = forms.CharField(widget=forms.HiddenInput())
    title = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)
    email = forms.CharField()

    def clean(self):
        cleaned_data = self.cleaned_data
        if cleaned_data.get('title', None) is None:
            raise forms.ValidationError('Title cannot be empty.')
        if cleaned_data.get('body', None) is None:
            raise forms.ValidationError('Description cannot be empty.')
        return cleaned_data

class ReplyForm(forms.Form):
    comment_id = forms.CharField(widget=forms.HiddenInput())
    body = forms.CharField(widget=forms.Textarea)
    email = forms.CharField()

    def clean(self):
        return self.cleaned_data

comments/views.py
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.context_processors import csrf
from django.views.decorators.csrf import csrf_exempt

from comments.forms import CommentForm, ReplyForm
from comments.models import Comment, Reply

def get_comments(request):
    # retriving comment parameters
    book = request.GET.get('book', '')
    chapter = request.GET.get('chapter', '')
    example = request.GET.get('example', '')
    page = request.GET.get('page', '')
    comments = Comment.objects.filter(book=book).filter(chapter=chapter).filter(example=example)
    context = {
        'comments': comments,
        'book': book,
        'chapter': chapter,
        'example': example,
        'page': page
    }
    return render(request, "comments/get_comments.html", context)

def new_comment(request):
    # saving the poted comment
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment()
            comment.book = form.cleaned_data.get("book")
            comment.chapter = form.cleaned_data.get("chapter")
            comment.example = form.cleaned_data.get("example")
            comment.page = form.cleaned_data.get("page")
            comment.title = form.cleaned_data.get("title")
            comment.body = form.cleaned_data.get("body")
            comment.email = form.cleaned_data.get("email", "Anonymous")
            comment.save()
            return HttpResponseRedirect(
                '/comments/get/?book={0}&chapter={1}&example={2}&page={3}'.format(
                    comment.book, comment.chapter, comment.example, comment.page
                )
            )
        else:
            book = request.POST.get('book', '')
            chapter = request.POST.get('chapter', '')
            example = request.POST.get('example', '')
            page = request.POST.get('page', '')
            return HttpResponseRedirect(
                '/comments/new/?book={0}&chapter={1}&example={2}&page={3}'.format(
                    book, chapter, example, page
                )
            )

    # retriving comment parameters
    book = request.GET.get('book', '')
    chapter = request.GET.get('chapter', '')
    example = request.GET.get('example', '')
    page = request.GET.get('page', '')
    initial_values = {
        'book': book,
        'chapter': chapter,
        'example': example,
        'page': page
    }
    form = CommentForm(initial = initial_values)
    context = {
        'form': form,
        'book': book,
        'chapter': chapter,
        'example': example,
        'page': page
    }
    context.update(csrf(request))
    return render(request, 'comments/new_comment.html', context)

def new_reply(request):
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            comment_id  = form.cleaned_data.get('comment_id')
            comment = Comment.objects.get(id=comment_id)
            reply = Reply()
            reply.comment = comment
            reply.body = form.cleaned_data.get('body')
            reply.email = form.cleaned_data.get('email', 'Anonymous')
            reply.save()
            return HttpResponseRedirect(
                '/comments/get/?book={0}&chapter={1}&example={2}&page={3}'.format(
                    comment.book, comment.chapter, comment.example, comment.page
                )
            )
        else:
            comment_id = request.POST.get('comment_id', '')
            return HttpResponseRedirect(
                '/comments/new-reply/?comment_id={0}'.format(
                    comment_id
                )
            )
    comment_id = request.GET.get('comment_id', '')
    comment = Comment.objects.get(id=comment_id)
    initial_values = {
        'comment_id': comment_id
    }
    form = ReplyForm(initial = initial_values)
    context = {
        'form': form,
        'comment': comment
    }
    return render(request, 'comments/new_reply.html', context)

comments/templates/comments/comment_base.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
  <head>
        <title>
       {% block title %}
       Python Textbook Companion Project | FOSSEE, IIT Bombay
       {% endblock %}
     </title>
   {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
   {% endblock %}
   
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" /> 
   <link rel ="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css"/>
   <link rel ="stylesheet" href="{% static 'css/comments.css' %}" type="text/css"/>
    <style>
        .module-list {
            float: left;
            height: 220px;
            margin-top: 20px;
            margin-bottom: 20px;
            margin-left: 50px;
            padding: 10px;
            padding-bottom: 25px;
            position: relative;
            width: 300px;
            background: #2c3e50;
        }
        .module-list img {
            height: 220px;
        }
        .module-list img:hover{
            height: 220px;
            border-radius: 15px;
        }

        .module-list a{
            color: #ffffff;
        }
       .navbar .container {
            max-width: 1100px;
        }
        #content-wrap{
            max-width: 1100px;
            margin: 0 auto;
        }
        input[type="text"] {
            width: 100%;
        }
        input[type="password"] {
            width: 100%;
        }
    </style>

   {% block css %}
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
   {% endblock %}

   {% block script %}
   {% endblock %}
   </head>

<body>
<div class="navbar navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Python Textbook Companion</a>
          <div class="nav-collapse collapse">

            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="http://fossee.in" target="_blank">FOSSEE</a></li>
                  <li><a href="http://python.fossee.in" target="_blank">Python Team</a></li>
                </ul>
              </li>
	      <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Textbooks<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'tbc:CompletedBooks' %}">Completed Books</a></li>
                  <li><a href="{% url 'tbc:BooksUnderProgress' %}">Books Under Progress</a></li>
                </ul>
              </li>
              <!--li><a href="{% url 'tbc:InternshipForms' %}">Internship Forms</a></li>

            {% if user %}
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.first_name }}<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'tbc:UserLogout' %}">Logout</a></li>
                    </ul>
                 </li>
            {% endif %}

            {% if reviewer %}
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ reviewer.first_name }} {{ reviewer.last_name }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'tbc:BookReview' %}">Review Books</a></li>
                      <li><a href="{% url 'tbc:UserLogout' %}">Logout</a></li>
                    </ul>
                 </li>
            {% endif %}

            {% if anonymous %}
                  <li><a href="{% url 'tbc:UserLogin' %}">Login</a></li>
                  <li><a href="{% url 'tbc:UserRegister' %}">Sign Up</a></li>
            {% endif %}<-->

            </ul> <!--/.nav  -->
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container" id="comments-container">
	{% block content %}
	{% endblock %}
    <div class="clearfix"></div>
      <hr>
      
      <footer>
        <center><p>&copy; FOSSEE - IIT Bombay 2014</p></center>
        <center><img src="{% static 'images/fossee.png' %}" width=100 height=70></center>
      </footer>

    </div> <!-- /container -->
    
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- google analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-44697375-2', 'fossee.in');
      ga('send', 'pageview');
    </script>
    <!-- / google analytics -->
  </body>
</html>

comments/templates/comments/get_comments.html
{% extends 'comments/comment_base.html' %}
{% block content %}

<div id="recent-comments-wrapper">
    {% if comments %}
    <h5 class="pull-left"><u>Recent comments</u></h5>
    <h3></h3>
    <a class="btn btn-primary btn-small pull-right" href="/comments/new/?book={{ book }}&chapter={{ chapter }}&example={{ example }}&page={{ page }}">
        + New comment
    </a>
    <div class="clearfix"></div>
    <p> Showing comments for: Book: <em>{{ book }}</em> / Chapter: <em>{{ chapter }}</em> / Example: <em>{{ example }}<em></p>
            <div class="accordion" id="accordion2">
                {% for comment in comments %}
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse{{ forloop.counter }}">
                            #{{ forloop.counter }} <em>{{ comment.title }}</em>
                        </a>
                    </div>
                    <div id="collapse{{ forloop.counter }}" class="accordion-body collapse">
                        <div class="accordion-inner">
                            <blockquote>
                                {{ comment.body }}
                                <small>{{ comment.email }}</small>
                            </blockquote>
                            <div class="replies">
                                {% if comment.reply_set.all %}
                                <h6><u>Recent replies</u></h6>
                                {% endif %}
                                {% for reply in comment.reply_set.all %}
                                <div class="reply">
                                    <p>{{ reply.body }}</p>
                                    <small> - {{ comment.email }}</small>
                                </div>
                                {% endfor %}
                                <a class="btn btn-success btn-small" href="/comments/new-reply/?comment_id={{ comment.id }}">+ Reply</a>
                            </div>
                        </div>
                    </div>
                </div> <!-- /.accordion-group  -->
                {% endfor %}
            </div> <!-- /.accordion -->
            {% else %}
            <center>
                <div class="well">
                    <h5>Book: {{ book }} / Chapter: {{ chapter }} / Example: {{ example }}</h5>
                <p> <em>Be the first one to create a comment for this example.</em> </p>
                <a class="btn btn-primary" href="/comments/new/?book={{ book }}&chapter={{ chapter }}&example={{ example }}&page={{ page }}">+ Create a new comment</a>
            </div>
            </center>
            {% endif %}
        </div> <!-- /#recent-comments-form -->
{% endblock %}

comments/templates/comments/new_comment.html
{% extends 'comments/comment_base.html' %}
{% block content %}
<div id="new-comment-form">
    <h5><u>New comment form</u></h5>
    <h4>Book: <em>{{ book }}</em> / Chapter: <em>{{ chapter }}</em> / Example: <em>{{ example }}</em> / Page: <em>{{ page }}</em></h4>
    <form action="/comments/new/" method="POST" accept-charset="utf-8"> {% csrf_token %}
        {{ form.errors }}
        {{ form.book }}
        {{ form.chapter }}
        {{ form.example }}
        {{ form.page }}
        <label>Comment Title:</label>
        {{ form.title }}<br>
        <label>Comment Description:</label>
        {{ form.body }} <br>
        <label>Email:</label>
        {{ form.email }} <br>
        <input class="btn btn-primary" type="submit" value="Submit">
        <a class="btn btn-default" href="/comments/get/?book={{ book }}&chapter={{ chapter }}&example={{ example }}&page={{ page }}">Cancel</a>
    </form>
</div> <!-- /#new-comment-form -->
{% endblock %}

comments/templates/comments/new_reply.html
{% extends 'comments/comment_base.html' %}
{% block content %}
<div id="new-reply-form">
    <u> Comment: </u> <br><br>
    <div class="well" style="width: 78%">
        <blockquote>
            {{ comment.body }}
            <small>{{ comment.email }}</small>
        </blockquote>
        <div class="replies">
            {% if comment.reply_set.all %}
            <h6><u>Recent replies</u></h6>
            {% endif %}
            {% for reply in comment.reply_set.all %}
            <div class="reply">
                <p>{{ reply.body }}</p>
                <small> - {{ reply.email }}</small>
            </div>
            {% endfor %}
        </div>
    </div>
    <h5><u>New reply form</u></h5>
    <form action="/comments/new-reply/" method="POST" accept-charset="utf-8"> {% csrf_token %}
        {{ form.errors }}
        {{ form.comment_id }}
        <label>Description:</label>
        {{ form.body }} <br>
        <label>Email:</label>
        {{ form.email }} <br>
        <input class="btn btn-primary" type="submit" value="Submit">
        <a class="btn btn-default" href="/comments/get/?book={{ comment.book }}&chapter={{ comment.chapter }}&example={{ comment.example }}&page={{ comment.page }}">Cancel</a>
    </form>
</div> <!-- /#new-comment-form -->
{% endblock %}