PythonTBC/urls.py
from django.conf.urls import patterns, include, url
import tbc_error_page.views
import commentingapp.views
import django.contrib.sitemaps.views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from .sitemap import TbcBookSitemap
sitemaps = { 
    'book': TbcBookSitemap, 
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'PythonTBC.views.home', name='home'),
    # url(r'^PythonTBC/', include('PythonTBC.foo.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin', include(admin.site.urls)),
    url(r'^', include('tbc.urls', namespace='tbc')),
    url(r'^sitemap\.xml$', django.contrib.sitemaps.views.sitemap, {'sitemaps': sitemaps}),

    url(r'^admin-tools/commenting', commentingapp.views.commenting, name = 'commenting'),
    url(r'^admin-tools/error_page', tbc_error_page.views.error, name = 'error_page'),
    url(r'^admin-tools/broken_page', tbc_error_page.views.broken, name = 'broken_page'),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]

tbc/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import tbc.views

urlpatterns = [
    url(r'^$', tbc.views.home, name='home'),
    url(r'^internship-forms/$', tbc.views.internship_forms, name='internship_forms'),
    url(r'^about-pythontbc/$', tbc.views.about_pytbc, name='about_pytbc'),
   
    url(r'^sample-notebook/$', tbc.views.sample_ipynb, name='sample_ipynb'),
    url(r'^register/$', tbc.views.user_register, name='user_register'),
    url(r'^login/$', tbc.views.user_login, name='user_login'),
    url(r'^logout/$', tbc.views.user_logout, name='user_logout'),
    url(r'^profile/$', tbc.views.user_profile, name='user_profile'),
    url(r'^update-profile/$', tbc.views.update_profile, name='update_profile'),
    url(r'^forgot-password/$', tbc.views.forgot_password, name='forgot_password'),
    url(r'^update-password/$', tbc.views.update_password, name='update_password'),
    url(r'^admin-tools/$', tbc.views.admin_tools, name='admin_tools'),    
   
    url(r'^submit-proposal/$', tbc.views.submit_proposal, name='submit_proposal'),
    url(r'^submit-aicte-proposal/$', tbc.views.list_aicte, name='list_aicte'),
    url(r'^submit-aicte-proposal/(?P<aicte_book_id>\d+)/$', tbc.views.submit_aicte_proposal, name='submit_aicte_proposal'),
    url(r'^submit-book/$', tbc.views.submit_book, name='submit_book'),
    url(r'^submit-sample/$', tbc.views.submit_sample, name='submit_sample'),
    url(r'^submit-sample/(?P<proposal_id>\d+)$', tbc.views.submit_sample, name='submit_sample'),
    url(r'^submit-sample/(?P<proposal_id>\d+)/(?P<old_notebook_id>\d+)$', tbc.views.submit_sample, name='submit_sample'),
    url(r'^confirm-book-details/$', tbc.views.confirm_book_details, name='confirm_book_details'),
    url(r'^submit-book-old/$', tbc.views.submit_book, name='submit_book'),
    url(r'^submit-code/$', tbc.views.submit_code, name='submit_code'),
    url(r'^submit-code-old/(?P<book_id>\d+)$', tbc.views.submit_code_old, name='submit_code_old'),
    url(r'^update-content/(?P<book_id>\d+)$', tbc.views.update_content, name='update_content'),
    url(r'^get-zip/(?P<book_id>\d+)$', tbc.views.get_zip, name='get_zip'),
    url(r'^browse-books/$', tbc.views.browse_books, name='browse_books'),
    url(r'^browse-books/(?P<category>.+)$', tbc.views.browse_books, name='browse_books'),
    url(r'^convert-notebook/(?P<notebook_path>.+)$', tbc.views.convert_notebook, name='convert_notebook'),
    url(r'^book-details/(?P<book_id>\d+)/$', tbc.views.book_details, name='book_details'),
	url(r'^completed-books/$', tbc.views.completed_books, name='completed_books'),
	url(r'^completed-books/(?P<category>.+)$', tbc.views.completed_books, name='completed_books'),
	url(r'^books-under-progress/$', tbc.views.books_under_progress, name='books_under_progress'),
	url(r'^redirect-ipynb/(?P<notebook_path>.+)$', tbc.views.redirect_to_ipynb, name='redirect_to_ipynb'),
	url(r'^get-certificate/$', tbc.views.get_certificate, name='get_certificate'),
	url(r'^get-certificate/(?P<book_id>\d+)/$', tbc.views.get_certificate, name='get_certificate'),
    
    
    url(r'^book-review/$', tbc.views.book_review, name='book_review'),
    url(r'^proposal-review/$', tbc.views.review_proposals, name='review_proposals'),
    url(r'^proposal-review/(?P<proposal_id>\d+)/(?P<textbook_id>\d+)$', tbc.views.review_proposals, name='review_proposals'),
    url(r'^disapprove-sample-notebook/(?P<proposal_id>\d+)$', tbc.views.disapprove_proposal, name='disapprove_proposal'),
    url(r'^allot-book/(?P<proposal_id>\d+)$', tbc.views.allot_book, name='allot_book'),
    url(r'^reject-proposal/(?P<proposal_id>\d+)$', tbc.views.reject_proposal, name='reject_proposal'),
    url(r'^book-review/(?P<book_id>\d+)$', tbc.views.book_review, name='book_review'),
    url(r'^approve-book/(?P<book_id>\d+)$', tbc.views.approve_book, name='approve_book'),
    url(r'^notify-changes/(?P<book_id>\d+)$', tbc.views.notify_changes, name='notify_changes'),
    url(r'^brokenbooks/$', tbc.views.get_broken_books, name='broken_books'),
    url(r'^link-image/$', tbc.views.link_image, name='link_image'),
    url(r'^books/$', tbc.views.books, name='books'),
    url(r'^edit-book/(?P<book_id>\d+)/$', tbc.views.edit_book, name='edit_book'),
    url(r'^books-fill-details/$', tbc.views.books_fill_details, name='books_fill_details'),
    url(r'^edit-books-fill-details/(?P<book_id>\d+)/$', tbc.views.edit_books_fill_details, name='edit_books_fill_details'),
    # ajax urls
    url(r'^ajax/matching-books/$', tbc.views.ajax_matching_books, name='AjaxMatchingBooks'),

]

tbc/views.py
from django.utils.encoding import force_text
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render_to_response, redirect
from django.views.decorators.csrf import csrf_exempt
from django.template.context_processors import csrf
from django.contrib.auth import authenticate, login, logout
from django.contrib.admin.models import CHANGE
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from .models import *
from tbc.forms import *
from . import local
import os
import zipfile
import io
import smtplib
import shutil
import string
import random
import json
import subprocess
from email.mime.text import MIMEText
import StringIO

def add_log(user, object, flag, message, proposal_id=None, chat='No message'):
    '''Creates log entry of the user activities.'''
    ActivityLog(
        user_id=user.id,
        content_type_id=ContentType.objects.get_for_model(object).id,
        object_id=object.id,
        object_repr=force_text(object),
        action_flag=flag,
        change_message=message,
        proposal_id = proposal_id,
        conversation = chat,
    ).save()


def email_send(to,subject,msg):
    try:
        smtpObj = smtplib.SMTP('localhost')
        mail_from = "textbook@fossee.in"
        message = MIMEText(msg)
        message['Subject'] = subject
        message['From'] = mail_from
        message['to'] = to
        smtpObj.sendmail(mail_from, to, message.as_string())
    except SMTPException:
        return HttpResponse("Error:unable to send email")


def is_reviewer(user):
    if user.groups.filter(name='reviewer').exists():
        return True


def internship_forms(request):
    context = {}
    images = []
    if request.user.is_anonymous():
        context['anonymous'] = True
    else:
        if is_reviewer(request.user):
            context['reviewer'] = request.user
        else:
            context['user'] = request.user
    return render_to_response('tbc/internship-forms.html', context)


def sample_ipynb(request):
    return render_to_response('tbc/sample.html')


def about_pytbc(request):
    context = {}
    images = []
    if request.user.is_anonymous():
        context['anonymous'] = True
    else:
        if is_reviewer(request.user):
            context['reviewer'] = request.user
        else:
            context['user'] = request.user
    return render_to_response('tbc/about-pytbc.html', context)


def home(request):
    context = {}
    images = []
    if request.user.is_anonymous():
        context['anonymous'] = True
    else:
        if is_reviewer(request.user):
            context['reviewer'] = request.user
        else:
            context['user'] = request.user
    if 'up' in request.GET:
        context['up'] = True
    if 'profile' in request.GET:
        context['profile'] = True
    if 'login' in request.GET:
        context['login'] = True
    if 'logout' in request.GET:
        context['logout'] = True
    if 'update_book' in request.GET:
        context['update_book'] = True
    if 'not_found' in request.GET:
        context['not_found'] = True
    if 'proposal' in request.GET:
        context['proposal_submitted'] = True
    if 'proposal_pending' in request.GET:
        context['proposal_pending'] = True
    if 'book_pending' in request.GET:
        context['book_pending'] = True
    if 'no_book_alloted' in request.GET:
        context['no_book_alloted'] = True
    if 'sample_notebook' in request.GET:
        context['sample_notebook'] = True
    if 'cannot_submit_sample' in request.GET:
        context['cannot_submit_sample'] =True
    if 'bookupdate' in request.GET:
        context['bookupdate'] =True

    books = Book.objects.filter(approved=True).order_by("-id")
    for book in books:
        try:
            images.append(ScreenShots.objects.filter(book=book)[0])
        except:
            return HttpResponse(book)
    context['images'] = images
    book_images = []
    for i in range(len(books)):
        obj = {'book':books[i], 'image':images[i]}
        book_images.append(obj)
    context['items'] = book_images

    #Check if user is logged in and fetch user's pending proposal ID
    if context.get('user'):
        curr_user = request.user
        user_profile = Profile.objects.filter(user=curr_user)

        pending_proposal_list = list(Proposal.objects.filter(status="pending").order_by('id'))
        try:
            pending_user_proposal = Proposal.objects.get(user=user_profile, status="pending")
        except:
            pending_user_proposal = None

        if pending_user_proposal:
            context['proposal_position'] = pending_proposal_list.index(pending_user_proposal) + 1

    return render_to_response('base.html', context)


def _checkprofile(user):
    return Profile.objects.filter(user=user).exists()


def user_login(request):
    context = {}
    context.update(csrf(request))
    if 'require_login' in request.GET:
        context['require_login'] = True
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        if username == "" or password == "":
            form = UserLoginForm()
            context['form'] = form
            context['empty'] = True
            return render_to_response('tbc/login.html', context)
        curr_user = authenticate(username=username, password=password)
        if curr_user is not None:
            login(request, curr_user)
            add_log(curr_user, curr_user, CHANGE, 'Logged in')
        else:
            form = UserLoginForm()
            context['form'] = form
            context['invalid'] = True
            return render_to_response('tbc/login.html', context)
        if is_reviewer(curr_user):
            context['reviewer'] = curr_user
            return HttpResponseRedirect("/book-review")
        else:
            context['user'] = curr_user
            try:
                Profile.objects.get(user=curr_user)
                return HttpResponseRedirect("/?login=success")
            except:
                return HttpResponseRedirect("/profile/?update=profile")
    else:
        form = UserLoginForm()
        if 'signup' in request.GET:
            context['signup'] = True
    context['form'] = form
    return render_to_response('tbc/login.html', context)


def user_register(request):
    context = {}
    context.update(csrf(request))
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            check_email = User.objects.filter(email=email)
            if check_email:
                context['form'] = form
                context['DuplicateEmail'] = True
                return render_to_response('tbc/register.html', context)
            else:
                user = form.save()
                add_log(user, user, CHANGE, 'Registered')
                return HttpResponseRedirect('/login/?signup=done')
        else:
            context = {}
            context.update(csrf(request))
            context['form'] = form
            return render_to_response('tbc/register.html', context)
    else:
        form = UserRegisterForm()
    context['form'] = form
    return render_to_response('tbc/register.html', context)


def user_profile(request):
    context = {}
    user = request.user
    if user.is_authenticated():
        user_profile = Profile.objects.filter(user=user)
        profile = user_profile[0] if user_profile.exists() else None
        if request.method == 'POST':
            form = UserProfileForm(request.POST, instance=profile)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = request.user
                data.save()
                add_log(user, user, CHANGE,'Profile entry')
                return HttpResponseRedirect('/')
            else:
                context.update(csrf(request))
                context['form'] = form
                return render_to_response('tbc/profile.html', context)
        form = UserProfileForm(instance=profile)
        context.update(csrf(request))
        context['form'] = form
        context['user'] = user
        if 'update' in request.GET:
            context['profile'] = True
        return render_to_response('tbc/profile.html', context)
    else:
        return HttpResponseRedirect('/login/?require_login=True')


def update_profile(request):
    user = request.user
    context = {}
    context.update(csrf(request))
    if user.is_anonymous():
        return HttpResponseRedirect('/login/?require_login=True')
    if not _checkprofile(user):
        return HttpResponseRedirect("/profile/?update=profile")
    context['user'] = user   
    user_profile = Profile.objects.get(user=user)
    if request.method == "POST":
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user
            data.save()
            add_log(user, user, CHANGE,'Profile entry')
            return HttpResponseRedirect('/')
        else:
            context['form'] = form
            return render_to_response('tbc/update-profile.html', context)
    else:
        form = UserProfileForm(instance=user_profile)
    context['form'] = form
    return render_to_response('tbc/update-profile.html', context)

def user_logout(request):
    user = request.user
    if user.is_authenticated() and user.is_active:
        logout(request)
    add_log(user, user, CHANGE, 'Logged out')
    return redirect('/?logout=done')


def forgot_password(request):
    context = {}
    user_emails = []
    context.update(csrf(request))
    if request.user.is_anonymous():
        context['anonymous'] = True
    if request.method == 'POST':
        email = request.POST['email']

tbc/templates/tbc/about-pytbc.html
{% extends "base.html" %}
{% load static %}

{% block script %}
    <script src="http://code.jquery.com/jquery-1.4.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            
            $("#objective").click(function(){
            $('#details').load('{% static "templates/objectives.html" %}');
            });

        
            $("#who").click(function(){
            $('#details').load('{% static "templates/who.html" %}');
            });

            $("#how").click(function(){
            $('#details').load('{% static "templates/how.html" %}');
            });

            $("#guidelines").click(function(){
            $('#details').load('{% static "templates/guidelines.html" %}');
            });

            $("#goodies").click(function(){
            $('#details').load('{% static "templates/goodie.html" %}');
            });

            $("#disclaimer").click(function(){
            $('#details').load('{% static "templates/disclaimer.html" %}');
            });

            $("#faqs").click(function(){
            $('#details').load('{% static "templates/faq.html" %}');
            });

            $("#contact").click(function(){
            $('#details').load('{% static "templates/contactus.html" %}');
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="well span3" style="width:18%;margin-left:5px;">
        <div class="nav nav-list">
            <ul>
                <li><a id="objective" href="#objective"><strong>Objective</strong></a></li>
                <li><a id="who" href="#who-can-contribute"><strong>Who can contribute ?</strong></a></li>
                <li><a id="how" href="#how-to-contribute"><strong>How to contribute ?</strong></a></li>
                <li><a id="guidelines" href="#guidelines"><strong>Guidelines for Coding</strong></a></li>
                <li><a id="goodies" href="#goodies"><strong>Goodies</strong></a></li>
                <li><a id="disclaimer" href="#disclaimer"><strong>Disclaimer</strong></a></li>
                <li><a id="faqs" href="#faqs"><strong>FAQs</strong></a></li>
                <li><a id="contact" href="#contact"><strong>Contact</strong></a></li>
            </ul>
        </div>
    </div>
    <div class="well span9" id="details" style="float:right;width:74%;margin-left:5px;min-height:150px;">
        <p>The Textbook Companion activity aims to create a repository of reference material for Python by coding solved examples of standard engineering textbooks using Python. This activity intends to,</p>
         <ul>
             <li>Make individuals learn Python through a practical approach</li>
             <li>Provide a huge database of Companions as a learning resource</li>
             <li>To make it easy for users of such textbooks to start using Python.</li>
             <li>To improve the documentation available for Python</li>
        </ul>
    </div>
</div>
{% endblock %}

tbc/templates/tbc/ajax-matching-books.html
<html>
<body>
<div>
    <span id="flag">{% if flag %}match exists{% endif %}</span>
    <div id="matches">
        <center><h5>The books you have proposed may already be <b>under progress</b> or <b>completed</b> by some other contributor. Kindly verify and submit the proposal.</h5></center>
        <hr>
        {% for match in matches %}
            {% if match %}
                <b><h5>Potential matching books for your book preference {{ forloop.counter }}</h5></b>
            {% else %}
                <h5>No matching books found for book preference {{ forloop.counter }}</h5>
            {% endif %}
            <ul>
            {% for book in match %}
                <li>{{ book.title }} by {{ book.author }}</li>
            {% endfor %}
            </ul>
            <hr>
        {% endfor %}
    </div>
</div>
</body>
</html>

tbc/templates/tbc/book-details.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% load staticfiles %}
<script src="{% static 'js/jquery.postcsrf.js' %}"></script>

{% load hitcount_tags %}
{% get_hit_count_js_variables for book as hitcount %}
<script type="text/javascript">
jQuery(document).ready(function($) {
  // use the template tags in our JavaScript call
  $.postCSRF("{{ hitcount.ajax_url }}", { hitcountPK : "{{ hitcount.pk }}" })
    .done(function(data){
      $('<i />').text(data.hit_counted).attr('id','hit-counted-value').appendTo('#hit-counted');
      $('#hit-response').text(data.hit_message);
  }).fail(function(data){
      console.log('POST failed');
      console.log(data);
  });
});
</script>
<script>
function redirectToIpynb(notebook)
{
    alert(notebook);
    notebook = notebook.split("/")
    alert("http://ipynb.fossee.in/notebooks/"+notebook[1]+"/"+notebook[2]);
    url = "http://ipynb.fossee.in/notebooks/"+notebook[1]+"/"+notebook[2]
    window.location.replace(url)
}
</script>
{% endblock %}

{% block content %}
<center><h3>{{ book.title }}</h3></center>
<div class="row-fluid">
{% for image in images %}
<span class="showonhover">  
    <div class ="module-list">
        <span class="hovertext">
            Click to view -{{ image.chapters_set.get.name }}
        </span>
        {% if image.chapters_set.get.notebook %}
            <a href="{% url 'tbc:convert_notebook' image.chapters_set.get.notebook %}"><img src="{% static 'Python-Textbook-Companions/' %}{{ image.image }}"></a></span>
        {% else %}
            <img src="{% static 'Python-Textbook-Companions/' %}{{ image.image }}">
        {% endif %}
        <center><p style="margin-top:30px;">{{ image.caption }}</p></center>
    </div>
{% endfor %}
</div>
<hr>
<div id="content-wrap">
<table class="table table-bordered table-hover">
<th>Chapters</th>
<th width=350>Download Links</th>
{% for chapter in chapters %}
    <tr>
        <td>
            <a href="{% url 'tbc:convert_notebook' chapter.notebook %}">{{ chapter.name }}</a>
        </td>
        <td>
            <a href="{% static 'Python-Textbook-Companions/' %}{{ chapter.notebook }}" download>Download</a>
        </td>
    </tr>
{% endfor %}
</table>
<hr>
<a class="btn btn-primary btn-large" href="{% url 'tbc:get_zip' book.id %}" style="float:right; margin-top:20px;">Download Book as Zip</a>
<table>
    <tr>
        <td>Author: &nbsp;&nbsp;</td>
        <td>{{ book.author }}</td>
 
    </tr>
    <tr>
        <td>Publisher: &nbsp;&nbsp;</td>
        <td>{{ book.publisher_place }}</td>
    </tr>
    <tr>
        <td>ISBN: &nbsp;&nbsp;</td>
        <td><a href= http://www.isbnsearch.org/isbn/{{ book.isbn }} target="_blank">{{ book.isbn }}</a></td>
    </tr>
    <tr>
        <td>Contributor: &nbsp;&nbsp;</td>
        <td>{{ book.contributor.user.first_name }} {{ book.contributor.user.last_name }}</td>
    </tr>
    <tr>
        <td>Institute/Organization: &nbsp;&nbsp;</td>
        <td>{{ book.contributor.insti_org }}</td>
    </tr>
    <tr>
        <td>Department/Designation: &nbsp;&nbsp;</td>
        <td>{{ book.contributor.dept_desg }}</td>
    </tr>
    <tr>
        <td>Reviewer: &nbsp;&nbsp;</td>
        <td>{{ book.reviewer.name }}</td>
    </tr>
    <tr>
        <td>GitHub: &nbsp;&nbsp;</td>
        <td><a href= 'https://github.com/FOSSEE/Python-Textbook-Companions/tree/master/{{ book.title.split|join:"_" }}_by_{{ book.author.split|join:"_" }}' target="_blank">{{ book.title }}</a></td>
    </tr>
<!--<tr>
        <td>Page Hits: &nbsp;&nbsp;</td>
<td>{% get_hit_count for book %}</td>

</tr>
-->
</table>

</div>

{% endblock %}

tbc/templates/tbc/books-fill-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if bookfill %}
<center>
        <div class="alert" style="width:230px;height:23px;">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <p>Book details updated</p>
        </div>
    </center>
{% endif %}
<div class="row-fluid">
    <div class="span6">
        <u> Books without details </u>
        <ol>
            {% for book in auto  %}
                <li><a href="{% url 'tbc:edit_books_fill_details' book.id %}"> {{ book.title }} </a> </li>
            {% endfor %}
        </ol>
        <br \>
      <!--  <u> Books with log available, so can be automated </u>
        <ol>
            {% for book in auto %}
                <li><a href="{% url 'tbc:edit_books_fill_details' book.id %}"> {{ book.title }} </a> </li>
            {% endfor %}
        </ol>-->
    </div>
    <div class="span6">
        <u> Books with details </u>
        <ol>
            {% for book in books_complete %}
                <li><a href="{% url 'tbc:edit_books_fill_details' book.id %}"> {{ book.title }} </a></li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}

tbc/templates/tbc/brokenbooks.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<script type="text/javascript">
function submitBook()
{
    document.forms.brokenbooks.submit();
}
</script>

{% endblock %}
{% block content %}
<center><h4>Select any book from the drop down below to fix the broken link:</h4></center>
<form name="brokenbooks" action="/brokenbooks/" method=POST enctype="multipart/form-data">
{% csrf_token %}
<center>
    <select style="border-color:black" name="books" id="books" onchange="submitBook()">
        <option value=0>Select Book</option>
        {% for book in books_to_link %}
        <option value={{ book.id }}>{{ book }}</option>
        {% endfor %}
    </select>
{% endblock %}

tbc/templates/tbc/disapprove-sample.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h3>Diapprove Sample Notebook</h3>
<hr>
<h4>Notifing Chages for book {{ proposal.accepted.title }} to {{ proposal.user.user.first_name }} {{ proposal.user.user.last_name }}</h4></center>
<form action="/disapprove-sample-notebook/{{ proposal.id }}" method=POST enctype="multipart/form-data">
{% csrf_token %}
    <table>
        <tr><td>To</td></tr>
        <tr><td><input type="text" value="{{ proposal.user.user.email }}" readonly></td></tr>
        <tr><td>Changes Required</td></tr>
        <tr><td><textarea rows="15" cols="100" name="changes_required" style="width:100%;"></textarea></td></tr>
        <tr><td><input class="btn btn-primary" type="submit" value="Send"></td></tr>
    </table>
</form>
{% endblock %}

tbc/templates/tbc/edit-book.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script>

$(document).ready(function() {
         console.log("rogkor")
    $(".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "2000:2030",
    });
  });
</script>
{% endblock %}
{% block content %}
<div class="well">
    <center><a href="{% url 'tbc:books' %}" class="btn btn-primary"> BACK </a></center>
    <form action="{% url 'tbc:edit_book' book.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <center><input class="btn btn-primary" type="submit" value="SAVE"></center>
    </form>
</div>

{% endblock %}

tbc/templates/tbc/link_image.html
{% extends 'base.html' %}
{% block content %}

    <center><font color='blue'><b>
    {% if success %}
        Thank you for your contribution.<br>
        Click <a href={% url 'tbc:brokenbooks' %}>Broken Books</a> to contribute further.<br>
    {% else %}
    Link image for the book
    {{ book.title }} by {{ book.author }}.<br>
    Select an appropriate chapter from the dropdown for the corresponding image.<br>
    You can verify using the chapters link given at the bottom.<br>
    Once you are sure, click on Submit button.
    </font></b>
    </center>
    <hr>
    <form action="/link-image/" method=POST enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="book" value={{book.id}}>
    <div class ="row-fluid">
    {% for screenshot in screenshots %}
    <!--<a href="/static/uploads/{{ screenshot.image }}" target="_blank">{{ screenshot }}</a>-->
        <div class ="module-list">
            <img src="/static/Python-Textbook-Companions/{{ screenshot.image }}">
            <br>
            <select style="border-color:black" name="chapters{{screenshot.id}}" id="chapters{{screenshot.id}}">
                {% for chapter in chapters %}
                    <option value={{ chapter.id }}>{{ chapter }}</option>
                {% endfor %}
            </select>
            <hr>
        </div>
    {% endfor %}
    </div>
    <br>
    <div >
        <b><u> Below are the links to the chapters:</u></b><br>

        {% for chapter in chapters %}
        <a href="{% url 'tbc:convert_notebook' chapter.notebook %}" target="_blank">{{ chapter }}</a>
        <br>
        {% endfor %}
    </div>
    <center><input class="btn btn-primary" type=submit value=submit></center>
    </form>
{% endif %}
{% endblock %}